[package]
name = "scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.11"
reqwest = "0.12.12"
serde = { version = "1.0.217", features = ["derive"] }
trust-dns-resolver = "0.23.2"
rayon = "1.10.0"
